### PR TITLE
Add Turkish Support

### PR DESCRIPTION
**Pull request by mzeyrek**
Created turkish language support

### CODE REVIEW

**Comment by Rello** [comment]
Hello,
thank you!
we will have a look and merge it for the next release.

**Review by ghost — COMMENTED** [review]
@mzeyrek We ask for changes and additions for version 2.3.0 before the release.

**Comment by mzeyrek** [comment]
If you have any other branch for newer version just let me know, i can merge there as well.

Btw, it's not a good place to write any issue but would be great if you can check an issue i'm facing https://github.com/nextcloud/server/issues/9039 can raise seperate issue here but first wanted to check with you whether relevant or not

**Comment by ghost** [comment]
@mzeyrek May you add the missing translations of the added strings in `tr.js` from line `35` to `44` please? Thank you!

**Comment by mzeyrek** [comment]
Sure no problem. Let me know anything else needs to be added, 
i also fixed a typo error in json file as well

**Review by ghost — APPROVED** [review]

**Review by Rello — APPROVED** [review]

**Comment by Rello** [comment]
thank you

**Pull request merged**
