### PR TITLE
use path from config when resolving playlist items

### LINKED ISSUE #495: Playlists do not work when library path is set
### Actual behavior
M3U playlists are detected but empty.

### Steps to reproduce the behavior
1. Enter a path in audioplayer scanner settings
2. Scan library
3. Select an M3U playlist

### Server configuration

**Nextcloud/ownCloud version:** (see `/status.php`)
18.0.7.1

**Audio Player version:** (see `/settings/apps`)
2.11.2

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
Yes, SMB.

#### Nextcloud/ownCloud log
The path reported as 'Final path of playlist track' is relative to the audio path specified in settings of audioplayer.

### Hacky Fix
The problem is in CategoryController::StreamParser. Inserting the missing part of the path before obtaining the fileID fixes the issue for me. This is probably not the best way to fix this, which is why I'm not supplying a PR.

### PR DESCRIPTION
**Pull request by zimj0**
fix #495

### CODE REVIEW

**Comment by Rello** [comment]
Hi,
thank you for this suggestion. actually it makes sense if using a folder. wonder why no one came up with this before.

but:
I think your position is not good.
It needs to be in the first "if", I guess
https://github.com/Rello/audioplayer/blob/702bcb555e1d321ad0aa1be7d859de01e5b739fa/lib/Controller/CategoryController.php#L494

because your approach makes sense for absolute file paths only. the other 2 cases of that if are relative paths. and they will be based on the (absolute nextcloud-)location of the playlist file. So this will have whatever music directory you have already attached.

what do you think?

**Comment by zimj0** [comment]
~~I'm not sure about absolute paths, in my library all playlists use relative path and they had this problem. After your comment I did some additional testing: It turns out, that the absolute path of the playlist file is not determined correctly by getInternalPath if the file is on external storage. I modified the fix to check if the folder path is already present in the string and only add it if not.~~

~~A quick test with absolute path also yielded the correct path. But files did not show up in the audioplayer playlist. I guess because the file was outside of the www folder and the webserver forbids access. Therefore, I'm not sure if absolute path is a relevant use case. Anyway it should be covered by this fix as well.~~

**Comment by zimj0** [comment]
Sorry, I was mistaken: The problem is not due to the folder specified in config, but due to external storage only.
So, turns out there is a much simpler and more general solution: Getting the full path of the playlist file. 
What do you think?

**Comment by Rello** [comment]
I will test locally also.
thank you

**Comment by Rello** [comment]
Hello,
how does this work for you?
"music" is my external storage folder (SMB) in files app

old: $streamfile[0]->getPath()
returns: /admin/files/music/playlist/relative.m3u

new: $streamfile[0]->getInternalPath()
returns: playlist/relative.m3u

Then the title needs to be matched to this position. in your case its missing the subfolder.
this can not work I would say

**Comment by Rello** [comment]
ok, it is solved. there was another issue!

https://github.com/Rello/audioplayer/blob/master/lib/Controller/CategoryController.php#L500-L501
first I was using `array_shift` which cut of the beginning - but I need to cut the folder off.
second I overwrote the $playlistFilePath which was supposed to be reused

can you try on your side?

**Comment by zimj0** [comment]
Hi, 

> old: $streamfile[0]->getPath()
> returns: /admin/files/music/playlist/relative.m3u

looks odd, did you mix up old and new?
The following code 
https://github.com/Rello/audioplayer/blob/master/lib/Controller/CategoryController.php#L454-L458
should turn /admin/files/music/playlist/relative.m3u
into music/playlist/relative.m3u

Regarding the case with relative path and '../' I can't say, because I do not have such playlists. 
Will test tomorrow.

**Comment by zimj0** [comment]
Can confirm working for relative path with '../'
Two levels up '../../'  is not working though. Maybe looping until the string contains no more '../' will do the trick?

**Comment by Rello** [comment]
Thats correct of course. 🤦🏼‍♂️

**Comment by Rello** [comment]
done

**Pull request merged**
