### PR TITLE
Implemented recording of disc number per song

### PR DESCRIPTION
**Pull request by Faldon**
# Added extracting of disc number tag
For storing the disc number, the database was extended to store the disc number in the track table.
Furthermore the edit metadata dialogue was extended to edit the disc number of a song.
The disc number column was added to the sort order when loading tracks.

### CODE REVIEW

**Comment by Rello** [comment]
Hello,
thank you for the suggestion. This will be a good backend preparation.
We will use the frontend-information later as requested with #88 and the new dynamic playlists, which we are currenlty working on

**Comment by Rello** [comment]
Hello @Faldon ,
did you test your implementation?
because getID3 does not deliver a `disc_number`!?

for id3v2 (mp3) it is `part_of_a_set`
for wma it is `partofset`
flac to be clarified

in this case, we need to loop across the different versions
https://github.com/Rello/audioplayer/blob/master/controller/scannercontroller.php#L550-L556
...please let me know...

**Comment by Faldon** [comment]
@Rello 
That's correct. I tested it just with m4a and ogg. Apologizes. I honestly thought, getID3 would normalize tag names when copied to comments. AFAIR, VorbisComments use tracknumber instead of track or track_number and couldn't find the loop for it in the code.
I will add the correct mappings to the merge request.

**Comment by Faldon** [comment]
Hi @Rello . Should looping be implemented for other tags too? FLAC does use a date tag instead of year for example.

**Comment by Rello** [comment]
Hello,
alsways check the code-search to find the tags which getID3 is returning.

possible returns are only:
part_of_a_set
partofset (without "a"!)
disc_number

for performance reasons, the most likely (mp3) should be the first of the loop.

Leave the other changes for now. We need to try to merge this pull asap because the NC12 compatibility is requiring a major structural change of the app which would render your pull unmergeable

**Comment by Faldon** [comment]
Good morning.
With the latest commits I rewrote the part as you proposed and dropped the 'discnumber' tag.

**Comment by Rello** [comment]
@Faldon 
as expected, this pull can not be merged anymore due to the deep changes for Nc12/oC10 compatibility.
I will include it manually and add the other ID3 fields which are also required

**Comment by Faldon** [comment]
@Rello 
Ok. Thank you for commenting. And thank you for the app in general. :-)

**Comment by Rello** [comment]
implemented with #184

**Pull request closed without merging**
