### PR TITLE
Show song info in title

### PR DESCRIPTION
**Pull request by mmatous**
Hi, I wrote this basically one-liner feature and did some light refactoring and fixing along the way, so I would not have to duplicate code.
You may not want the last commit as I did not see you using let, const or template literals anywhere in JS, but I don't know whether you are actively avoiding them or just not used to using them.

### CODE REVIEW

**Comment by Rello** [comment]
Hello,
thank you! I will have a look.

the reason against LET is the compatibility.
older iOS devices for example don´t support it. as my primary usecase for AP are the kids` older iPads, this part can not be implemented.

**Comment by mmatous** [comment]
2nd version 
Added missing semicolon in my code.
Swapped lets for vars.
Did I understand correctly that you use snake case for sort or private helper methods and camel case for what would be public interface? I was a bit confused about seeing both in one file and did not know what to use for my function.

**Comment by Rello** [comment]
`snake case for sort or private helper methods and camel case` 
Hey,
thank you for coming back. as you might notice, I am not a pro JS dev.
If you have any suggestion how to do it correct and consistent across the whole app, I will be happy to accept the suggestions and do a proper cleanup!

are you referring to something like this?
https://en.wikipedia.org/wiki/Naming_convention_(programming)#Java

**Comment by mmatous** [comment]
> are you referring to something like this?
> https://en.wikipedia.org/wiki/Naming_convention_(programming)#Java

Yes, pretty much. Just like in any other language pick one thing and stick with it. Does not mattern what you pick in the end, as long as you are consistent. If you use a style that is commonly known and accepted even better. Even better than that, use eslint and push eslint config file in your repo so anyone can see in their IDEs what you want. You might have to tweak the file a bit since you use jQuery.
In addition eslint might reveal other problems in your code.

**Pull request merged**
