### PR TITLE
small css changes for navigation-menu

### PR DESCRIPTION
**Pull request by artemanufrij**
some `margin`, `padding`, `flexbox` improvements

before:
screenshot_20170501_221206

after:
screenshot_20170501_221255

### CODE REVIEW

**Comment by Rello** [comment]
Hello,
thank you for the pull. Did you check the display on mobile devices already, that its still working?

**Comment by Rello** [comment]
Hello @artemanufrij 
I think the padding of the Album icon does not fit the layout. 
you realigned all playlists and the input box - but then the Grid-Icon was moved out of context. As the display is either "Albums" or "Selector" they need to be in one level.

could you move this back to the left?
The alignment of the other items/buttons looks much better with you fix

**Comment by artemanufrij** [comment]
@Rello I will do it tonight...

**Comment by artemanufrij** [comment]
@Rello Hey, Ich habe das Icon so ausgerichtet, wie es in den anderen Apps ebenfalls der Fall ist (u.a. Files / Aktivität). Wenn ich das Icon nach links verschiebe, dann schaut es (mMn) nicht "harmonisch" aus, da die Abstände - oben, link, unten - unterschiedlich sind.
Ich positioniere es gerne wieder weiter nach links. Ich wollte nur meine Absicht kurz erläutern...

oder was meinst Du?

**Comment by Rello** [comment]
Hallo @artemanufrij 
I think this screenshot shows the issue pretty well. the perfect solution would be to have everything (letters) in one line - now we have 3 different levels.
can you do the magic?

ap_nav-align_2

**Comment by artemanufrij** [comment]
@Rello 
spectacle ni4787

**Comment by Rello** [comment]
Hello,
I think we have quite some chaos now :-)
left = now; right = before

- Alignment of Grid-Icon: OK
- Space between Grid and dropdown: gone - NOK
- Spacing between playlists (here smart = others e.g. genre): too big. We need to keep the users with 100s of genres/albums/artists in mind. raising the spacing is not advised
- Spacing between Smart Lists and own lists: gone - NOK
- own lists now have an offset which would indicate a hierarchical order: NOK
- Editing of playlists not aligned anymore: NOK

screen shot 2017-05-03 at 20 57 13

screen shot 2017-05-03 at 21 02 33

what do you think?
currently I only see the Album/Grid part as mergeable

**Comment by artemanufrij** [comment]
wow.... give me a moment...

**Comment by artemanufrij** [comment]
@Rello could you test it please...
screenshot_20170503_214921

**Comment by ghost** [comment]
@artemanufrij You have more than a moment. We appreciate your improvements. Moving style code from PHP to CSS is a clean solution. I have a special look at the mobile use of the Audio Player app.

**Comment by artemanufrij** [comment]
@xraMsamohT could you test last commit please?

**Review by Rello — APPROVED** [review]

**Comment by ghost** [comment]
@artemanufrij That's very good! Thank your for your quick work!

**Pull request merged**
