### PR TITLE
Specify code requirements

### PR DESCRIPTION
**Pull request by mmatous**
This is an initial version of what I would like to become AP's lint config.  Most rules are just based on current state of the code (or most of it) while others on [NC recommendations](https://docs.nextcloud.com/server/stable/developer_manual/general/codingguidelines.html#javascript) and my personal opinions.
I also included predefined globals based on their use in the code, but I could not find any mention of them in NC docs. Could you point me in the right direction?
I also picked ecmaVersion 6 as target version which is according to [caniuse](https://caniuse.com/#feat=es6) well supported (95%+ of browsers out there) and brings nice features like modules, arrow functions or proper classes.
Thoughts, comments?

### CODE REVIEW

**Comment by Rello** [comment]
still WIP or you want to merge already?

**Comment by mmatous** [comment]
That depends mostly on you. You mentioned you wanted backward compatibility for a specific iOS browser, so I thought you will want some modifications or exceptions to be made.
Const, let and template literals I used in one of my previous PRs are also part of ES6.

**Comment by Rello** [comment]
you seem to be deeper in this topic. I would need to work myself into this.
could you add the part that "let" would not be required? then I will see if there is more. but thats the obvious.

thank you

**Comment by mmatous** [comment]
If you tell me what is the exact version of iOS that the code is required to be compatible with, I can make the rules more accurate.

**Comment by Rello** [comment]
ah. ok.
its iOS 9.3.5 => Safari 9

**Comment by mmatous** [comment]
Disallowing certain features in eslint would require writing plugins for custom rules. I ended up just outling the requirements in another document.
It's not as clean, but unless there is a whole crowd of contributors waiting to break those requirements, the time-cost trade-off is better.

**Pull request merged**
