### PR TITLE
Remove useless execution bit

### PR DESCRIPTION
**Pull request by r4sas**
Some files contain useless execution bit. That PR removes it from them.

Signed-off-by: r4sas <r4sas@i2pmail.org>

### CODE REVIEW

**Comment by Rello** [comment]
Hi,
what should this pull do?
do you mean execution flag on the file level (e.g. chmod +x?)
the pull did not change anything to any file. I think this is not valid here because this property is not part of a package delivery?!

**Comment by r4sas** [comment]
> what should this pull do?
> do you mean execution flag on the file level (e.g. chmod +x?)

Yes, that pull removes execution flag on files which have it in repository.

> the pull did not change anything to any file. I think this is not valid here because this property is not part of a package delivery?!

I don't know how Nextcloud creates packages with applications, or parsing them, but I see that files installed from applications manager doesn't have that `x` bit on files. That's why I consider to remove it in repository too because they mustn't be executable when you calling them from terminal for example.

**Comment by Rello** [comment]
so, what to do? I can merge it, but this will not solve your issue.
I think it can't be in the package .tg anyway as the same files will run on linux & windows and the later one does not know that flag. 
I guess its something that NC does during install and should be the same with all apps?

**Comment by r4sas** [comment]
FYI: example with [Nextcloud Mail](https://github.com/nextcloud/mail) app repository:
```
$ find . -type f -executable -print
./.git/hooks/applypatch-msg.sample
./.git/hooks/commit-msg.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/pre-commit.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/pre-receive.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/update.sample
./l10n/preproc.sh
```

> I guess its something that NC does during install and should be the same with all apps?

Maybe

**Pull request merged**
